# Generated by Django 4.2 on 2023-04-26 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_consume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consume',
            old_name='food_cosumed',
            new_name='food_consumed',
        ),
    ]
