# Generated by Django 4.2 on 2023-06-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_alter_calorielimit_calorie_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calorielimit',
            name='timestamp',
            field=models.DateField(auto_now=True),
        ),
    ]
